version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 1.17
        NODE_VERSION: none
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000
    
    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

      # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: redis:6
    restart: unless-stopped
    # Runs Redis on the same network as the app container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:app
    environment:
      - REDIS_PORT=6379
      - REDIS_PASSWORD=

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    network_mode: service:app
    volumes:
      - ./prometheus.yml