name: Build

on:
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  APP_ID: 189572

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: build
      run: make build

    - name: test
      run: make test
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
