name: Test

on:
  workflow_dispatch:
    inputs:
      installation:
        description: 'GitHub App Installion #'
        required: true
  workflow_call:
    inputs:
      installation:
        description: 'GitHub App Installion #'
        required: true
        type: string


env:
  DOMAIN_NAME: prometheus.carbonhub.io
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Generare instance name
        id: instanceName
        run: |
          x=12
          echo "instanceName=$x" >> $GITHUB_OUTPUT
      - name: check
        run: echo ${{ steps.instanceName.outputs.instanceName }}
